---

# reddit-app configuration
reddit_app_db_host: "{{ hostvars['reddit-db']['gce_private_ip'] }}"

# nginx reverse proxy configuration
nginx_events_params:
  - worker_connections 1024
  - use epoll
  - multi_accept on

nginx_configs:
  proxy:
    - proxy_set_header X-Real-IP  $remote_addr
    - proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for

nginx_http_params:
  - sendfile on
  - access_log /var/log/nginx/access.log

nginx_sites:
  puma:
    - listen 80
    - server_name _
    - location / { proxy_pass  http://127.0.0.1:9292; include /etc/nginx/proxy_params; }
